# Generated by Django 3.2 on 2023-12-13 11:02

from django.db import migrations, models
import users.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserYamDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Электронная почта')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Имя пользователя')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
                ('role', models.CharField(choices=[('admin', 'ADMIN'), ('user', 'USER'), ('moderator', 'MODERATOR')], default=users.enums.UserRole['USER'], max_length=20, verbose_name='Роль')),
                ('confirmation_code', models.CharField(max_length=6)),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': '',
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
