# Generated by Django 3.2 on 2023-12-14 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_useryamdb_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useryamdb',
            name='role',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('user', 'USER'), ('moderator', 'MODERATOR')], default='user', max_length=20, verbose_name='Роль'),
        ),
    ]
